### ISSUE TITLE
App crashes after fetching number of articles

### ISSUE THREAD

**Issue by binerf** [nilsbraden/ttrss-reader-fork#412]
Hi all,

Since last "git pull" on my TTrss instance (v20.02-06b9d3966), app (on 2 different devices) downloaded from f-droid continuously crashes just after retrieving number of articles.

Here the logcat from one of my equipment:
<code>
<<< log_count = 28 >>>
[02-13 20:06:38.631 3367:5237 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttrssreader/.gui.CategoryActivity bnds=[959,927][1272,1163]} from uid 10033

[02-13 20:06:38.679 3367:3394 I/ActivityManager]
Start proc 9550:org.ttrssreader/u0a190 for activity org.ttrssreader/.gui.CategoryActivity

[02-13 20:06:38.689 9550:9550 E/org.ttrssreade]
Not starting debugger since process cannot load the jdwp agent.

[02-13 20:06:38.920 3367:3391 I/ActivityManager]
Displayed org.ttrssreader/.gui.CategoryActivity: +270ms

[02-13 20:06:39.073 750:2028 W/SurfaceFlinger]
Attempting to set client state on removed layer: Splash Screen org.ttrssreader#0

[02-13 20:06:39.073 750:2028 W/SurfaceFlinger]
Attempting to destroy on removed layer: Splash Screen org.ttrssreader#0

[02-13 20:06:39.225 750:878 W/SurfaceFlinger]
Attempting to set client state on removed layer: Surface(name=AppWindowToken{3c73d15 token=Token{95206cc ActivityRecord{77d98ff u0 org.ttrssreader/.gui.CategoryActivity t655}}})/@0x2868ae8 - animation-leash#0

[02-13 20:06:39.225 750:878 W/SurfaceFlinger]
Attempting to destroy on removed layer: Surface(name=AppWindowToken{3c73d15 token=Token{95206cc ActivityRecord{77d98ff u0 org.ttrssreader/.gui.CategoryActivity t655}}})/@0x2868ae8 - animation-leash#0

[02-13 20:06:43.190 9550:9584 E/AndroidRuntime]
FATAL EXCEPTION: AsyncTask #3
Process: org.ttrssreader, PID: 9550
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at d.e.g.c.done(:4)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Expected an int but was NULL at line 1 column 69 path $.content[0].unread
	at c.b.a.i.a.j(Unknown Source:126)
	at d.e.e.d.a(:6)
	at d.e.a.c.a(:61)
	at org.ttrssreader.gui.CategoryActivity$b.a(:21)
	at d.e.g.b.call(:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

[02-13 20:06:43.206 3367:17944 W/ActivityManager]
  Force finishing activity org.ttrssreader/.gui.CategoryActivity

[02-13 20:06:43.400 750:878 W/SurfaceFlinger]
Attempting to destroy on removed layer: AppWindowToken{3c73d15 token=Token{95206cc ActivityRecord{77d98ff u0 org.ttrssreader/.gui.CategoryActivity t655}}}#0

[02-13 20:06:43.411 3367:5239 I/ActivityManager]
Process org.ttrssreader (pid 9550) has died: cch  CRE 

[02-13 20:07:45.966 3367:17944 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=org.ttrssreader/.gui.CategoryActivity} from uid 10033

[02-13 20:07:46.017 3367:3394 I/ActivityManager]
Start proc 9740:org.ttrssreader/u0a190 for activity org.ttrssreader/.gui.CategoryActivity

[02-13 20:07:46.035 9740:9740 E/org.ttrssreade]
Not starting debugger since process cannot load the jdwp agent.

[02-13 20:07:46.268 3367:3391 I/ActivityManager]
Displayed org.ttrssreader/.gui.CategoryActivity: +298ms

[02-13 20:07:46.432 750:1170 W/SurfaceFlinger]
Attempting to set client state on removed layer: Surface(name=AppWindowToken{39d82c5 token=Token{704153c ActivityRecord{ee1b2f u0 org.ttrssreader/.gui.CategoryActivity t655}}})/@0x5f887ed - animation-leash#0

[02-13 20:07:46.432 750:1170 W/SurfaceFlinger]
Attempting to destroy on removed layer: Surface(name=AppWindowToken{39d82c5 token=Token{704153c ActivityRecord{ee1b2f u0 org.ttrssreader/.gui.CategoryActivity t655}}})/@0x5f887ed - animation-leash#0

[02-13 20:07:46.433 750:878 W/SurfaceFlinger]
Attempting to set client state on removed layer: Splash Screen org.ttrssreader#0

[02-13 20:07:46.433 750:878 W/SurfaceFlinger]
Attempting to destroy on removed layer: Splash Screen org.ttrssreader#0

[02-13 20:07:50.109 9740:9764 E/AndroidRuntime]
FATAL EXCEPTION: AsyncTask #1
Process: org.ttrssreader, PID: 9740
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at d.e.g.c.done(:4)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Expected an int but was NULL at line 1 column 69 path $.content[0].unread
	at c.b.a.i.a.j(Unknown Source:126)
	at d.e.e.d.a(:6)
	at d.e.a.c.a(:61)
	at org.ttrssreader.gui.CategoryActivity$b.a(:21)
	at d.e.g.b.call(:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

[02-13 20:07:50.114 3367:4001 W/ActivityManager]
  Force finishing activity org.ttrssreader/.gui.CategoryActivity

[02-13 20:07:50.153 3367:3653 W/InputDispatcher]
channel '5b03b2b org.ttrssreader/org.ttrssreader.gui.CategoryActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[02-13 20:07:50.153 3367:3653 E/InputDispatcher]
channel '5b03b2b org.ttrssreader/org.ttrssreader.gui.CategoryActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

[02-13 20:07:50.154 3367:3648 I/WindowManager]
WIN DEATH: Window{5b03b2b u0 org.ttrssreader/org.ttrssreader.gui.CategoryActivity}

[02-13 20:07:50.154 3367:3648 W/InputDispatcher]
Attempted to unregister already unregistered input channel '5b03b2b org.ttrssreader/org.ttrssreader.gui.CategoryActivity (server)'

[02-13 20:07:50.154 3367:5239 I/ActivityManager]
Process org.ttrssreader (pid 9740) has died: cch  CRE 

[02-13 20:07:50.160 750:878 W/SurfaceFlinger]
Attempting to destroy on removed layer: AppWindowToken{39d82c5 token=Token{704153c ActivityRecord{ee1b2f u0 org.ttrssreader/.gui.CategoryActivity t655}}}#0
</code>

**Comment by nilsbraden** [comment]
Can't reproduce with current HEAD from git. Is this still an issue?

**Comment by binerf** [comment]
Hello,

git pull done today and still the same issue
