### ISSUE TITLE
Crash upon backing out to top of folder structure

### ISSUE THREAD

**Issue by nilsbraden** [nilsbraden/ttrss-reader-fork#425]
Stacktrace provided by Mail (thanks to Frank and David for reporting this!):

```
09-27 03:02:27.196  1989  2723 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
09-27 03:02:27.202  1989  3711 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{9ab2b71 org.ttrssreader} is now in focus and seems to be in full-screen mode
09-27 03:02:27.202  1989  3711 E ActivityTrigger: activityResumeTrigger: not whiteListedorg.ttrssreader/org.ttrssreader.gui.CategoryActivity/1958
09-27 03:02:27.243 31100 31100 D AndroidRuntime: Shutting down VM
--------- beginning of crash
09-27 03:02:27.250 31100 31100 E AndroidRuntime: FATAL EXCEPTION: main
09-27 03:02:27.250 31100 31100 E AndroidRuntime: Process: org.ttrssreader, PID: 31100
09-27 03:02:27.250 31100 31100 E AndroidRuntime: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class <unknown>
09-27 03:02:27.250 31100 31100 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
09-27 03:02:27.250 31100 31100 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.p.i.b.b(:1)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.q.c.b(Unknown Source:12)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.q.c.c(:12)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.p.i.g.i(Unknown Source:43)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.p.i.b.j(Unknown Source:12)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.q.c.j(Unknown Source:0)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.p.i.g.q(:1)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.p.i.g.y(Unknown Source:11)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.k.v$a.run(:1)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:778)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:710)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6589)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f04000f a=-1}
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:1212)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:818)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at c.b.q.z.<init>(Unknown Source:4)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	at androidx.appcompat.view.menu.ActionMenuItemView.<init>(:1)
09-27 03:02:27.250 31100 31100 E AndroidRuntime: 	... 27 more
```

**Comment by ftobin** [comment]
I'm getting still getting errors, but now it's slightly different.  Instead of crashing, I get "TTRSS-Reader has stopped", which is similar, but slightly different.

**Comment by nilsbraden** [comment]
Next attempt at fixing this: https://github.com/nilsbraden/ttrss-reader-fork/releases/tag/v1.96.1_1961
Thanks for testing! 👍

**Comment by ftobin** [comment]
Same message "TTRSS-Reader has stopped".
[out.txt](https://github.com/nilsbraden/ttrss-reader-fork/files/5324057/out.txt)

**Comment by flyser** [comment]
Same issue for me. It started to appear after I upgraded to android 11
