### ISSUE TITLE
1.96.4 crashes immediately after start, java.lang.NullPointerException: sslSocketFactory == null

### ISSUE THREAD

**Issue by fschlich** [nilsbraden/ttrss-reader-fork#450]
Since updating to 1.96.4 (I think), the app crashes immediately after starting it. There is an attempt to draw a window, but it doesn't last long enough for me to hit a button, enter settings etc. `adb logcat` has this (filtered on pid 18216)

```
05-13 13:52:46.634   725   725 D Zygote  : Forked child process 18216
05-13 13:52:46.639  1466  1813 I ActivityManager: Start proc 18216:org.ttrssreader/u0a110 for activity {org.ttrssreader/org.ttrssreader.gui.CategoryActivity}
05-13 13:52:46.676 18216 18216 E org.ttrssreade: Not starting debugger since process cannot load the jdwp agent.
05-13 13:52:46.779 18216 18216 I Perf    : Connecting to perf service.
05-13 13:52:46.830 18216 18238 I a       : initialize SSL: Trust certificates from keystore
05-13 13:52:46.832 18216 18238 I m       : Enabling SSLUtils to trust certificates from private keystore.
05-13 13:52:46.889 18216 18245 W DynamiteModule: Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
05-13 13:52:46.896 18216 18245 I DynamiteModule: Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
05-13 13:52:46.896 18216 18245 W ProviderInstaller: Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
05-13 13:52:46.990 18216 18245 I org.ttrssreade: The ClassLoaderContext is a special shared library.
05-13 13:52:46.995 18216 18216 D n       : GetNetworkType: Type = 3 (0 = none, 1 = mobile, 2 = metered, 3 = wifi)
05-13 13:52:46.997 18216 18243 I DpmTcmClient: RegisterTcmMonitor from: $Proxy0
05-13 13:52:46.999 18216 18245 I org.ttrssreade: The ClassLoaderContext is a special shared library.
05-13 13:52:47.009 18216 18245 I org.ttrssreade: The ClassLoaderContext is a special shared library.
05-13 13:52:47.025 18216 18243 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
05-13 13:52:47.036 18216 18216 D n       : GetNetworkType: Type = 3 (0 = none, 1 = mobile, 2 = metered, 3 = wifi)
05-13 13:52:47.074 18216 18216 D AndroidRuntime: Shutting down VM
05-13 13:52:47.075 18216 18216 E AndroidRuntime: FATAL EXCEPTION: main
05-13 13:52:47.075 18216 18216 E AndroidRuntime: Process: org.ttrssreader, PID: 18216
05-13 13:52:47.075 18216 18216 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.ttrssreader/org.ttrssreader.gui.CategoryActivity}: java.lang.NullPointerException: sslSocketFactory == null
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4206)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4238)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7403)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
05-13 13:52:47.075 18216 18216 E AndroidRuntime: Caused by: java.lang.NullPointerException: sslSocketFactory == null
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at e.e.e.d.<init>(:16)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at e.e.a.a.i(Unknown Source:13)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at e.e.b.l.D(:2)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at org.ttrssreader.gui.CategoryActivity.D(Unknown Source:0)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at e.e.b.l.onResume(:9)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:7946)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4196)
05-13 13:52:47.075 18216 18216 E AndroidRuntime:        ... 11 more
05-13 13:52:47.228 18216 18216 I Process : Sending signal. PID: 18216 SIG: 9
05-13 13:52:47.245   808   808 E lowmemorykiller: Error writing /proc/18216/oom_score_adj; errno=22
05-13 13:52:47.253   725   725 I Zygote  : Process 18216 exited due to signal 9 (Killed)
05-13 13:52:47.259  1466  4516 I ActivityManager: Process org.ttrssreader (pid 18216) has died: vis+99 TOP 
05-13 13:52:47.259  1466  1816 I libprocessgroup: Successfully killed process cgroup uid 10110 pid 18216 in 0ms
```

I've since uninstalled, installed 1.96.3 from FDroid, encountered #448, uninstalled, rebooted, installed 1.96.4 from Play Store. Now I no longer see this crash, but #448 continues to be a problem.

**Comment by nilsbraden** [comment]
Sadly that stacktrace was not recorded with 1.96.4, I can't read it with the corresponding mapping file. There are other reports in the play store with this stacktrace though:

java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4906)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4949)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:190)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:105)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2458)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8387)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
Caused by: java.lang.NullPointerException: 
  at okhttp3.OkHttpClient$Builder.sslSocketFactory (OkHttpClient.java)
  at org.ttrssreader.net.JSONConnector.initHttpClient (JSONConnector.java)
  at org.ttrssreader.net.JSONConnector.<init> (JSONConnector.java)
  at org.ttrssreader.controllers.Controller.getConnector (Controller.java:13)
  at org.ttrssreader.gui.MenuActivity.doRefresh (MenuActivity.java)
  at org.ttrssreader.gui.CategoryActivity.doRefresh (CategoryActivity.java)
  or                     .getCategoryListFragment (CategoryActivity.java)
  or                     .getFeedListFragment (CategoryActivity.java)
  at org.ttrssreader.gui.MenuActivity.refreshAndUpdate (MenuActivity.java)
  at org.ttrssreader.gui.MenuActivity.onResume (MenuActivity.java)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1472)
  at android.app.Activity.performResume (Activity.java:8258)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4896)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4949)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:190)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:105)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2458)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8387)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)

I'll push the release tomorrow.
