### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Marcs1987** [nilsbraden/ttrss-reader-fork#465]
I just installed TTRSS-Reader version 1.97.1 from Fdroid. I tried to configure it to connect to my own TTRSS instance that sits on an onion-address. I'm running Orbot on the same device and it acts as a proxy. I filled in all the settings in TTRSS-Reader for the connection. But it wouldn't connect. I was a bit pressed for time so I didn't debug it further then. Now the problem is that it always crashes when I try to start it. Attaching the stack trace.

type: crash
osVersion: google/redfin/redfin:13/TQ2A.230405.003/2023041100:user/release-keys
package: org.ttrssreader:1971
process: org.ttrssreader
processUptime: 183 + 266 ms

java.lang.RuntimeException: Unable to resume activity {org.ttrssreader/org.ttrssreader.gui.CategoryActivity}: android.os.NetworkOnMainThreadException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4777)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4810)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1667)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getByName(InetAddress.java:1106)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:235)
	at c5.d.<init>(SourceFile:184)
	at s4.a.e(Unknown Source:13)
	at org.ttrssreader.gui.a.A(SourceFile:15)
	at org.ttrssreader.gui.CategoryActivity.A(SourceFile:1)
	at org.ttrssreader.gui.a.onResume(SourceFile:77)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1569)
	at android.app.Activity.performResume(Activity.java:8520)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4767)
	... 15 more

**Comment by Marcs1987** [comment]
I noticed this other similar issue
https://github.com/nilsbraden/ttrss-reader-fork/issues/449
And when I installed version 1.95.7 I got it working

Even if the TTRSS-Reader no longer supports onion-addresses, it would be nice if the app wouldn't crash at startup if the user had set some preferences in the app that are no longer supported.
